const SET_USERS = 'SET_USERS';
const REG_USER = 'REG_USER';

const CREATE_BOARD = 'CREATE_BOARD';
const CREATE_COLUMN = 'CREATE_COLUMN';
const CHANGE_INPUT_VALUE = 'CHANGE_INPUT_VALUE';
const CHANGE_BLUR_INPUT_VALUE = 'CHANGE_BLUR_INPUT_VALUE';
const REMOVE_STATE = 'REMOVE_STATE'


export { SET_USERS, REG_USER, CHANGE_INPUT_VALUE, CHANGE_BLUR_INPUT_VALUE, CREATE_BOARD, CREATE_COLUMN, REMOVE_STATE };
