const SET_USERS = 'SET_USERS';
const SET_AUTH_USER = 'SET_AUTH_USER';
const REG_USER = 'REG_USER';

const CREATE_BOARD = 'CREATE_BOARD';
const BOARD_INPUT_VALUE = 'BOARD_INPUT_VALUE';

const CHANGE_INPUT_VALUE = 'CHANGE_INPUT_VALUE';
const CHANGE_BLUR_INPUT_VALUE = 'CHANGE_BLUR_INPUT_VALUE';
const SET_TASKS = 'SET_TASKS';
const FILTER_TASKS = 'FILTER_TASKS';

export { SET_USERS, SET_AUTH_USER, REG_USER, CHANGE_INPUT_VALUE, CHANGE_BLUR_INPUT_VALUE, SET_TASKS, FILTER_TASKS, CREATE_BOARD, BOARD_INPUT_VALUE };
